### PR TITLE
Fix scrolling to relevant records in search, filter all that doesnt m…

### LINKED ISSUE #1474: New HTML format: Search shows the most unrelevant results first
Dokka version: 1.4.10-dev-72
I use 1.4.10/stdlib.
When typing 'compare' in search, the list of results is scrolled down and shows the most unrelevant results:
I'm not sure it worths showing such results in the list at all (coincidence is 1 letter in each word).
image

### PR DESCRIPTION
**Pull request by MarcinAman**
…atch required amout of letters

closes #1474

### CODE REVIEW

File: plugins/base/frontend/src/main/components/search/dokkaFuzzyFilter.tsx [hunk 1]
```diff
@@ -66,7 +72,7 @@ export class DokkaFuzzyFilterComponent extends Select {
                     rank: SearchRank.NameMatch
                 }
             })
-            .filter((record: OptionWithSearchResult) => record.matched)
+            .filter((record: OptionWithSearchResult) => record.matched && (hasApproperateLenght(record, 3) || filterPhrase === ''))
```
Comment (MarcinAman) [inline plugins/base/frontend/src/main/components/search/dokkaFuzzyFilter.tsx:75]: Is a sequence of 3 a good idea? So basically it will discard every record that doesn't have at least 3 characters in sequence matched

File: plugins/base/frontend/src/main/components/search/dokkaFuzzyFilter.tsx [hunk 2]
```diff
@@ -38,6 +39,11 @@ const highlightMatchedPhrases = (records: OptionWithSearchResult[]): OptionWithH
     })
 }
 
+const hasApproperateLenght = (searchResult: OptionWithSearchResult, length: number): boolean => {
```
Comment (dolik-rce) [inline plugins/base/frontend/src/main/components/search/dokkaFuzzyFilter.tsx:42]: "Approperate" is not a word. I think you meant "appropriate".

Comment (MarcinAman) [reply plugins/base/frontend/src/main/components/search/dokkaFuzzyFilter.tsx]: Fair point, as i read this PR again i think this name was flawed from the beginning. Changed to something i found more descriptive: `hasAnyMatchedPhraseLongerThan`

**Review by Kordyjan — APPROVED** [review]
