### PR TITLE
Simplify Gradle Plugin

### LINKED ISSUE #995: Dokka MPP: Source set autoconfiguration
Dokka should be able to auto-configure inside a multiplatform project. It should at leat show a easy to understand error if something is misconfigured.

### LINKED ISSUE #1106: AbstractDokkaTask: Mark output directory as `Output`

### LINKED ISSUE #1107: DokkaTask: Use file API instead of strings

### LINKED ISSUE #1108: Fallback main source set: False positive "UP-TO-DATE"
Changes in the fallback main source set are unknown to Gradle since this source set is only created during task execution.

### LINKED ISSUE #1113: Subprojects Gradle config should accept typed project references instead of strings
The Dokka Gradle plugin supports aggregating output from multiple sub projects into a single generated site/artifact by specifying the sub projects to include via the `subProjects` property. However, this property takes a collection of raw strings. It is not obvious what the format should be for these: fully-qualified project paths? Just the leaf project name? The answer is documented in the README, but if you do the wrong thing, the Dokka task will just fail silently (since it doesn't fail if you specify non-existent projects).

I propose this configuration should accept Gradle project objects instead. This is more self-documenting, and stronger typed, so Gradle will actually fail with a more helpful error message if you do the wrong thing.

### LINKED ISSUE #1114: Support specifying subprojects via exclude list or pattern
The Dokka Gradle config currently supports generating output for multiple subprojects via the `subProjects` property. However, this is an include list. For library projects that consist of many modules, most of which need documentation to be generated, it would be helpful to have more sophisticated ways of specifying the subproject set. 

For example, I work on a project that has around 12 different library modules/projects, and a bunch of sample app modules. All the sample modules are grouped under a separate directory. The config I would like to write is to simply say "include all subprojects except children of the `:samples` project".

This is possible to do by filtering and mapping Gradle's list of projects, but that's a lot of wiring code to write and Gradle's APIs aren't always intuitive here. However, this approach would already be a lot easier to get right if the subProjects property took actual project references instead of raw strings (#1113).

### LINKED ISSUE #1274: "./" sourceLink path doesn't work
```kotlin
plugins {
    kotlin("jvm") version "1.4.0-rc"
    id("org.jetbrains.dokka")  version "1.4.0-rc"
}
repositories {
    jcenter()
}
tasks.dokkaHtml {
    dokkaSourceSets {
        create("main") {
            sourceLink {
                path = "./"
                url = "https://google.com"
                lineSuffix = "#L"
            }
        }
    }
}
```
image

but with:
```kotlin
path = "src/main/kotlin"
```
image

### LINKED ISSUE #1285: Compiler should not be bundled into `kotlin-analysis-intellij`

### LINKED ISSUE #1286: Use Property/Provider APIs in Dokka Public API

### LINKED ISSUE #1287: Use Provider/Property API to track configuration of the Kotlin Gradle Plugin
Updates/Configuration of the Kotlin Gradle plugin shall be live in the configuration for Dokka

### LINKED ISSUE #1288: Rename `Multimodule` to `MultiModule` in Gradle Plugin

### LINKED ISSUE #1289: DokkaMultiMouduleTask/DokkaCollectorTask: Proper error message if no child tasks are configured/found
Any DokkaMultiModuleTask or DokkaCollectorTask shall guide the user with a proper error message if either no child task is configured or can be found (e.g. because Dokka Gradle plugin is not applied to subrpojects)

### LINKED ISSUE #1290: DokkaMultiModuleTask output should be in a single output directory
Currently, the `DokkaMultiMoudleTask` is just linking to the output directories of the child dokka tasks. This is highly impractical, since those paths are separated a lot and often include file strucutres like "../.../childModle/build/...". 

We want to provide a file-layout that is "compact", which can easily be published on any web-server.

### LINKED ISSUE #1291: Use `ConfigureableFileCollection` instead of custom `SourceRoot` type
SourceRoot type shall be removed (in favour of `java.io.File` and `ConfigurableFileCollection`

### LINKED ISSUE #1292: Use `Set` instead of `List` in configuration whenever distinct entries are required

### PR DESCRIPTION
**Pull request by sellmair**
Closes #1108 
Closes #1107 
Closes #995 
Closes #1113 
Closes #1114 
Closes #1285 
Closes #1286
Closes #1287 
Closes #1288 
Closes #1289 
Closes #1290 
Closes #1291 
Closes #1292
Closes #1274
Closes #1106

### CODE REVIEW

File: core/src/main/kotlin/defaultConfiguration.kt [hunk 1]
```diff
@@ -37,19 +40,21 @@ data class DokkaSourceSetImpl(
...
+    override val docFile: File
 ) : DokkaConfiguration.DokkaModuleDescription
 
 data class SourceRootImpl(
-    override val path: String
-) : DokkaConfiguration.SourceRoot
+    override val directory: File
+) : DokkaConfiguration.SourceRoot {
+    constructor(directoryPath: String) : this(File(directoryPath))
+}
```
Comment (kamildoleglo) [inline core/src/main/kotlin/defaultConfiguration.kt:57]: IMHO we can drop the `SourceRoot` abstraction entirely. It's there for historical reasons (it had more than one property) but it makes Gradle configuration harder (you can't just pass a list of files to `sourceRoots` property) and I personally don't see any advantages of having this wrapper

Comment (sellmair) [reply core/src/main/kotlin/defaultConfiguration.kt:57]: 👍 Very, very reasonable!

Comment (sellmair) [reply core/src/main/kotlin/defaultConfiguration.kt]: Done ✅

File: core/src/main/kotlin/configuration.kt [hunk 2]
```diff
@@ -65,55 +74,50 @@ fun DokkaConfigurationImpl(json: String): DokkaConfigurationImpl = parseJson(jso
...
+    val pluginsClasspath: Set<File>
     val pluginsConfiguration: Map<String, String>
 
     interface DokkaSourceSet : Serializable {
         val sourceSetID: DokkaSourceSetID
         val displayName: String
         val moduleDisplayName: String
-        val classpath: List<String>
-        val sourceRoots: List<SourceRoot>
+        val classpath: Set<File>
```
Comment (Kordyjan) [inline core/src/main/kotlin/configuration.kt:90]: I know that it shouldn't matter in the perfect world, but sadly most developers at least once encountered a project that depended on the order of compiler classpath. If we treat classpath as a set we can introduce unresolved types in dokka, for projects that are compiling and working.
I think for this one field we should return to the interface that requires ordering.

File: core/src/main/kotlin/defaultExternalLinks.kt [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+fun ExternalDocumentationLink.Companion.androidSdk(): ExternalDocumentationLinkImpl {
+    return ExternalDocumentationLink("https://developer.android.com/reference/")
+}
+
+fun ExternalDocumentationLink.Companion.androidX(): ExternalDocumentationLinkImpl {
+    return ExternalDocumentationLink(
+        url = URL("https://developer.android.com/reference/kotlin/"),
+        packageListUrl = URL("https://developer.android.com/reference/androidx/package-list")
+    )
+}
```
[the remark this answers is not in the document]
Comment (sellmair) [reply core/src/main/kotlin/defaultExternalLinks.kt:31]: Thanks a lot ☺️ 👍

File: core/src/main/kotlin/configuration.kt (hunk 2 above)
Comment (sellmair) [reply core/src/main/kotlin/configuration.kt]: Pushed a commit to change from `Set` to `List`.

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/KotlinSourceSetGist.kt [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+internal data class KotlinSourceSetGist(
+    val name: String,
+    val platform: KotlinPlatformType,
+    val isMain: Boolean,
+    val classpath: FileCollection,
+    val sourceRoots: FileCollection,
+    val dependentSourceSetNames: Provider<Set<String>>,
+)
+
+internal fun Project.gistOf(sourceSet: KotlinSourceSet): KotlinSourceSetGist {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/KotlinSourceSetGist.kt:18]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/isMainSourceSet.kt [hunk 5]
```diff
@@ -0,0 +1,24 @@
+package org.jetbrains.dokka.gradle.kotlin
+
+import com.android.build.gradle.api.ApplicationVariant
+import com.android.build.gradle.api.LibraryVariant
+import org.gradle.api.Project
+import org.jetbrains.kotlin.gradle.plugin.KotlinSourceSet
+import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinJvmAndroidCompilation
+
+internal fun Project.isMainSourceSet(sourceSet: KotlinSourceSet): Boolean {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/isMainSourceSet.kt:9]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
+import org.jetbrains.kotlin.gradle.dsl.KotlinSingleTargetExtension
+import org.jetbrains.kotlin.gradle.plugin.KotlinSourceSet
+
+internal typealias KotlinCompilation =
+        org.jetbrains.kotlin.gradle.plugin.KotlinCompilation<KotlinCommonOptions>
+
+internal fun Project.allCompilationsOf(
+    sourceSet: KotlinSourceSet
+): List<KotlinCompilation> {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt:15]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt [hunk 7]
```diff
@@ -0,0 +1,34 @@
...
+    return when (val kotlin = kotlin) {
+        is KotlinMultiplatformExtension -> kotlin.allCompilationsOf(sourceSet)
+        is KotlinSingleTargetExtension -> kotlin.allCompilationsOf(sourceSet)
+        else -> emptyList()
+    }
+}
+
+internal fun Project.compilationsOf(sourceSet: KotlinSourceSet): List<KotlinCompilation> {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt:23]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt [hunk 8]
```diff
@@ -0,0 +1,34 @@
...
+    return allCompilationsOf(sourceSet).filter { compilation -> sourceSet in compilation.kotlinSourceSets }
+}
+
+private fun KotlinMultiplatformExtension.allCompilationsOf(sourceSet: KotlinSourceSet): List<KotlinCompilation> {
+    val allCompilations = targets.flatMap { target -> target.compilations }
+    return allCompilations.filter { compilation -> sourceSet in compilation.allKotlinSourceSets }
+}
+
+private fun KotlinSingleTargetExtension.allCompilationsOf(sourceSet: KotlinSourceSet): List<KotlinCompilation> {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt:32]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinSourceSetUtils.kt [hunk 9]
```diff
@@ -0,0 +1,13 @@
+package org.jetbrains.dokka.gradle.kotlin
+
+import org.jetbrains.kotlin.gradle.plugin.KotlinSourceSet
+
+
+internal fun KotlinSourceSet.withAllDependentSourceSets(): Sequence<KotlinSourceSet> {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinSourceSetUtils.kt:6]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/sourceSetKotlinGistConfiguration.kt [hunk 10]
```diff
@@ -0,0 +1,28 @@
+@file:Suppress("UnstableApiUsage")
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/sourceSetKotlinGistConfiguration.kt:1]: I think there's no `UnstableApi` here

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt [hunk 11]
```diff
@@ -0,0 +1,78 @@
+package org.jetbrains.dokka.gradle
+
+import org.jetbrains.dokka.*
+import org.jetbrains.dokka.DokkaConfiguration.ExternalDocumentationLink
+import java.io.File
+
+internal fun GradleDokkaSourceSetBuilder.toDokkaSourceSetImpl(): DokkaSourceSetImpl {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt:7]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt [hunk 12]
```diff
@@ -0,0 +1,78 @@
...
+        languageVersion = languageVersion.getSafe(),
+        apiVersion = apiVersion.getSafe(),
+        noStdlibLink = noStdlibLink.getSafe(),
+        noJdkLink = noJdkLink.getSafe(),
+        suppressedFiles = suppressedFilesWithDefaults(),
+        analysisPlatform = platform.getSafe()
+    )
+}
+
+private fun GradleDokkaSourceSetBuilder.moduleNameOrDefault(): String {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt:34]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt [hunk 13]
```diff
@@ -0,0 +1,78 @@
...
+private fun GradleDokkaSourceSetBuilder.displayNameOrDefault(): String {
+    displayName.getSafe()?.let { return it }
+    if (name.endsWith("Main") && name != "Main") {
+        return name.removeSuffix("Main")
+    }
+
+    return name
+}
+
+private fun GradleDokkaSourceSetBuilder.externalDocumentationLinksWithDefaults(): Set<ExternalDocumentationLinkImpl> {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt:47]: `=`

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/utils.kt [hunk 14]
```diff
@@ -3,10 +3,40 @@ package org.jetbrains.dokka.gradle
...
+
+internal infix fun <T> Property<T>.by(value: Provider<T>) {
+    this.set(value)
+}
+
+internal infix fun <T> HasMultipleValues<in T>.by(values: Iterable<T>) {
+    this.set(values)
+}
+
+internal fun parsePath(path: String): Path {
```
Comment (kamildoleglo) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/utils.kt:27]: `=`

File: core/src/main/kotlin/configuration.kt [hunk 15]
```diff
@@ -45,12 +44,22 @@ enum class Platform(val key: String) {
...
     }
 }
 
+interface DokkaConfigurationBuilder<T : Any> {
+    fun build(): T
+}
+
+fun <T : Any> Iterable<DokkaConfigurationBuilder<T>>.build(): List<T> {
+    return this.map { it.build() }
+}
```
[the remark this answers is not in the document]
Comment (sellmair) [reply core/src/main/kotlin/configuration.kt:61]: ✅

File: core/src/main/kotlin/defaultExternalLinks.kt [hunk 16]
```diff
@@ -0,0 +1,31 @@
+package org.jetbrains.dokka
+
+import org.jetbrains.dokka.DokkaConfiguration.ExternalDocumentationLink
+import java.net.URL
+
+
+fun ExternalDocumentationLink.Companion.jdk(jdkVersion: Int): ExternalDocumentationLinkImpl {
+    return ExternalDocumentationLink(
```
[the remark this answers is not in the document]
Comment (sellmair) [reply core/src/main/kotlin/defaultExternalLinks.kt:8]: ✅

File: core/src/main/kotlin/defaultExternalLinks.kt [hunk 17]
```diff
@@ -0,0 +1,31 @@
...
+        url =
+        if (jdkVersion < 11) "https://docs.oracle.com/javase/${jdkVersion}/docs/api/"
+        else "https://docs.oracle.com/en/java/javase/${jdkVersion}/docs/api/java.base/",
+        packageListUrl =
+        if (jdkVersion < 11) "https://docs.oracle.com/javase/${jdkVersion}/docs/api/package-list"
+        else "https://docs.oracle.com/en/java/javase/${jdkVersion}/docs/api/element-list"
+    )
+}
+
+fun ExternalDocumentationLink.Companion.kotlinStdlib(): ExternalDocumentationLinkImpl {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply core/src/main/kotlin/defaultExternalLinks.kt:18]: ✅

File: core/src/main/kotlin/defaultExternalLinks.kt [hunk 18]
```diff
@@ -0,0 +1,31 @@
...
+    return ExternalDocumentationLink("https://kotlinlang.org/api/latest/jvm/stdlib/")
+}
+
+fun ExternalDocumentationLink.Companion.androidSdk(): ExternalDocumentationLinkImpl {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply core/src/main/kotlin/defaultExternalLinks.kt:22]: ✅

File: core/src/main/kotlin/defaultExternalLinks.kt [hunk 19]
```diff
@@ -0,0 +1,31 @@
...
+    return ExternalDocumentationLink("https://developer.android.com/reference/")
+}
+
+fun ExternalDocumentationLink.Companion.androidX(): ExternalDocumentationLinkImpl {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply core/src/main/kotlin/defaultExternalLinks.kt:26]: ✅

File: plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt [hunk 20]
```diff
@@ -43,8 +43,8 @@ class DefaultPsiToDocumentableTranslator(
 
     override fun invoke(sourceSet: DokkaSourceSet, context: DokkaContext): DModule {
 
-        fun isFileInSourceRoots(file: File) : Boolean {
-            return sourceSet.sourceRoots.any { root -> file.path.startsWith(File(root.path).absolutePath) }
+        fun isFileInSourceRoots(file: File): Boolean {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply plugins/base/src/main/kotlin/translators/psi/DefaultPsiToDocumentableTranslator.kt:46]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt [hunk 21]
```diff
@@ -1,45 +1,83 @@
...
+    @Input
+    val pluginsConfiguration: MapProperty<String, String> = project.objects.mapProperty()
 
     @Classpath
     val plugins: Configuration = project.maybeCreateDokkaPluginConfiguration(name)
 
     @Classpath
     val runtime: Configuration = project.maybeCreateDokkaRuntimeConfiguration(name)
 
+    final override fun doFirst(action: Action<in Task>): Task {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt:52]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt [hunk 22]
```diff
@@ -1,45 +1,83 @@
...
+        return super.doFirst(action)
+    }
+
+    final override fun doFirst(action: Closure<*>): Task {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaTask.kt:56]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleFileLayout.kt [hunk 23]
```diff
@@ -0,0 +1,84 @@
...
+     * @return The target output directory of the [child] dokka task referenced by [parent]. This should
+     * be unique for all registered child tasks.
+     */
+    fun targetChildOutputDirectory(parent: DokkaMultiModuleTask, child: AbstractDokkaTask): File
+
+    /**
+     * Will link to the original [AbstractDokkaTask.outputDirectory]. This requires no copying of the output files.
+     */
+    object NoCopy : DokkaMultiModuleFileLayout {
+        override fun targetChildOutputDirectory(parent: DokkaMultiModuleTask, child: AbstractDokkaTask): File {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleFileLayout.kt:25]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleFileLayout.kt [hunk 24]
```diff
@@ -0,0 +1,84 @@
...
+            val relativeFilePath = relativeProjectPath.replace(":", File.separator)
+            check(!File(relativeFilePath).isAbsolute) { "Unexpected absolute path $relativeFilePath" }
+            return parent.outputDirectory.getSafe().resolve(relativeFilePath)
+        }
+    }
+}
+
+internal fun DokkaMultiModuleTask.targetChildOutputDirectory(
+    child: AbstractDokkaTask
+): File {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleFileLayout.kt:49]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleTask.kt [hunk 25]
```diff
@@ -0,0 +1,72 @@
...
+    @get:InputFiles
+    internal val sourceChildOutputDirectories: Iterable<File>
+        get() = childDokkaTasks.map { task -> task.outputDirectory.getSafe() }
+
+    @get:OutputDirectories
+    internal val targetChildOutputDirectories: Iterable<File>
+        get() = childDokkaTasks.map { task -> targetChildOutputDirectory(task) }
+
+    @Internal
+    override fun getTaskDependencies(): TaskDependencyInternal {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleTask.kt:43]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleTask.kt [hunk 26]
```diff
@@ -0,0 +1,72 @@
...
+        return super.getTaskDependencies() + childDokkaTasks
+    }
+
+    override fun generateDocumentation() {
+        checkChildDokkaTasksIsNotEmpty()
+        copyChildOutputDirectories()
+        super.generateDocumentation()
+    }
+
+    override fun buildDokkaConfiguration(): DokkaConfigurationImpl {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaMultiModuleTask.kt:53]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaProperty.kt [hunk 27]
```diff
@@ -0,0 +1,21 @@
...
+
+internal inline fun <reified T : Any> ObjectFactory.safeProperty() = property<T?>()
+
+internal inline fun <reified T : Any> Property<T?>.safeConvention(value: T): Property<T> {
+    @Suppress("UnstableApiUsage")
+    return this.convention(value).cast()
+}
+
+@OptIn(ExperimentalStdlibApi::class)
+internal inline fun <reified T> Provider<T>.getSafe(): T {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaProperty.kt:18]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt [hunk 28]
```diff
@@ -0,0 +1,220 @@
...
+
+    @InputFiles
+    val suppressedFiles: ConfigurableFileCollection = project.files()
+
+    @Input
+    @Optional
+    val platform: Property<Platform> = project.objects.safeProperty<Platform>()
+        .safeConvention(Platform.DEFAULT)
+
+    fun DokkaSourceSetID(sourceSetName: String): DokkaSourceSetID {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt:124]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt [hunk 29]
```diff
@@ -0,0 +1,220 @@
...
+            GradleExternalDocumentationLinkBuilder(project).apply {
+                this.url by url
+                if (packageListUrl != null) {
+                    this.packageListUrl by packageListUrl
+                }
+            }
+        )
+    }
+
+    override fun build(): DokkaSourceSetImpl {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt:208]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleExternalDocumentationLinkBuilder.kt [hunk 30]
```diff
@@ -0,0 +1,27 @@
...
+class GradleExternalDocumentationLinkBuilder(
+    @Transient @get:Internal internal val project: Project
+) : DokkaConfigurationBuilder<ExternalDocumentationLinkImpl> {
+    @Input
+    val url: Property<URL?> = project.objects.safeProperty()
+
+    @Input
+    val packageListUrl: Property<URL?> = project.objects.safeProperty()
+
+    override fun build(): ExternalDocumentationLinkImpl {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleExternalDocumentationLinkBuilder.kt:21]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleSourceLinkBuilder.kt [hunk 31]
```diff
@@ -0,0 +1,35 @@
...
+    @Input
+    val remoteUrl: Property<String> = project.objects.safeProperty<String>()
+        .safeConvention("")
+
+    @Optional
+    @Input
+    val remoteLineSuffix: Property<String> = project.objects.safeProperty<String>()
+        .safeConvention("#L")
+
+    override fun build(): SourceLinkDefinitionImpl {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleSourceLinkBuilder.kt:28]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/TaskDependencyInternalWithAdditions.kt [hunk 32]
```diff
@@ -0,0 +1,20 @@
+package org.jetbrains.dokka.gradle
+
+import org.gradle.api.Task
+import org.gradle.api.internal.tasks.AbstractTaskDependency
+import org.gradle.api.internal.tasks.TaskDependencyInternal
+import org.gradle.api.internal.tasks.TaskDependencyResolveContext
+
+internal operator fun TaskDependencyInternal.plus(tasks: Iterable<Task>): TaskDependencyInternal {
```
[the remark this answers is not in the document]
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/TaskDependencyInternalWithAdditions.kt:8]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/isMainSourceSet.kt (hunk 5 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/isMainSourceSet.kt:9]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt (hunk 7 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt:23]: ❌

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt (hunk 8 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinCompilationUtils.kt:32]: :x:

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinSourceSetUtils.kt (hunk 9 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/kotlin/kotlinSourceSetUtils.kt:6]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/sourceSetKotlinGistConfiguration.kt (hunk 10 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/sourceSetKotlinGistConfiguration.kt:1]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt (hunk 11 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt:7]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt (hunk 12 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt:34]: :x:

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt (hunk 13 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/toDokkaSourceSetImpl.kt:47]: :x:

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/utils.kt (hunk 14 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/utils.kt:27]: ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaParentTask.kt [hunk 33]
```diff
@@ -0,0 +1,86 @@
...
+abstract class AbstractDokkaParentTask(
+    bootstrapClass: KClass<out DokkaBootstrap> = DokkaBootstrapImpl::class
+) : AbstractDokkaTask(bootstrapClass) {
+
+    @get:Internal
+    internal var childDokkaTaskPaths: Set<String> = emptySet()
+        private set
+
+    @get:Nested
+    internal val childDokkaTasks: Set<AbstractDokkaTask>
```
Comment (jjohannes) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaParentTask.kt:20]: A task inside a task does not seem right. Why is this needed?

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaCollectorTask.kt [hunk 34]
```diff
@@ -1,59 +1,29 @@
 package org.jetbrains.dokka.gradle
 
-import com.google.gson.GsonBuilder
-import org.gradle.api.plugins.JavaBasePlugin.DOCUMENTATION_GROUP
-import org.gradle.api.tasks.Input
-import org.jetbrains.dokka.toJsonString
+import org.jetbrains.dokka.DokkaConfigurationImpl
 
-open class DokkaCollectorTask : AbstractDokkaTask() {
+open class DokkaCollectorTask : AbstractDokkaParentTask() {
```
Comment (jjohannes) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaCollectorTask.kt:5]: Probably just 💄 , but I would recommend making all task classes abstract instead of open.

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaProperty.kt [hunk 35]
```diff
@@ -0,0 +1,21 @@
+package org.jetbrains.dokka.gradle
+
+import org.gradle.api.model.ObjectFactory
+import org.gradle.api.provider.Property
+import org.gradle.api.provider.Provider
+import org.gradle.kotlin.dsl.property
+import org.jetbrains.dokka.utilities.cast
+import kotlin.reflect.typeOf
+
+internal inline fun <reified T : Any> ObjectFactory.safeProperty() = property<T?>()
```
Comment (jjohannes) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaProperty.kt:10]: Why do you need these extension methods and can not use `property<T>()` directly? It's already `<T>` not `<T?>`.

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt [hunk 36]
```diff
@@ -0,0 +1,218 @@
...
+    @Optional
+    val classpath: ConfigurableFileCollection = project.files()
+
+    @Input
+    @Optional
+    val moduleDisplayName: Property<String?> = project.objects.safeProperty()
+
+    @Input
+    @Optional
+    val displayName: Property<String?> = project.objects.safeProperty()
```
Comment (jjohannes) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt:45]: You should use Property<String> here. A property can always be _unset_ and usually that should be enough and there shouldn't be the need to set it to null. You can still use `@Optional` to state that _unset_ is a valid state.

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt [hunk 37]
```diff
@@ -0,0 +1,218 @@
...
+
+    @InputFiles
+    val sourceRoots: ConfigurableFileCollection = project.files()
```
Comment (jjohannes) [inline runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt:48]: Instead of `objects.fileCollection()` would be the better API if you just need an empty collection (If it is available in the Gradle version you want to support).

Even better would be to make the class and all the properties abstract. Like:
```
    @get:InputFiles
    abstract val sourceRoots: ConfigurableFileCollection
```

Then Gradle will inject everything and you have much less boilerplate. And you probably won't have to pass `project` and/or `objects` around.

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaProperty.kt (hunk 35 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaProperty.kt:10]: This is an interesting question: 
So the issue that I have with properties is, that it was really hard for me to track whether or not I expect some value being present in a Property, or if it is actually, truly "optional". The current implementation of `Property` also does not care. It is like "can be there, might not". 

Therefore, I started tracking my expectations of any `Property` myself in the Type-System: 
The convention internally here is: 

- `Property<T?>` -> No value required
- `Property<T>`  -> Fail if value is missing

See this  `getSafe` method, that I am using everywhere. This will use `orNull` if the type T is optional and `get` otherwise.

```
@OptIn(ExperimentalStdlibApi::class)
internal inline fun <reified T> Provider<T>.getSafe(): T =
    if (typeOf<T>().isMarkedNullable) orNull as T
    else get()

```

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt (hunk 36 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt:45]: You mean I should use a Kotlin property? `var displayName: String? = null`

Comment (jjohannes) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt:45]: Term _property_ is quite overloaded. :)

This is what I mean:

`val displayName: Property<String> = project.objects.property()`

or, if you can make the class abstract, just:

`abstract val displayName: Property<String>`

Comment (jjohannes) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt:45]: Now I saw the other comment, which answers why you use `<String?>`. I'll answer there later.

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt (hunk 37 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/GradleDokkaSourceSetBuilder.kt:48]: Thanks a lot, I did not know about `objects.fileCollection` and I also did not know about the fact, that Gradle will inject into Abstract classes here as well, which is awesome!! 🤪

Pushed a commit for `objects.fileCollection`. Making this object abstract will require some tests to be adapted. I will wait for another PR to be merged first to tackle this! :)

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaCollectorTask.kt (hunk 34 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/DokkaCollectorTask.kt:5]: Thanks for the hint! ☺️ 
Pushed a commit to change this ✅

File: runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaParentTask.kt (hunk 33 above)
Comment (sellmair) [reply runners/gradle-plugin/src/main/kotlin/org/jetbrains/dokka/gradle/AbstractDokkaParentTask.kt:20]: This kind of "parent" tasks are managing multiple "child" tasks. Accessing them like this is not just there for convenience. While not all parent tasks do have task dependencies on its children, they should still re-run if any of the child's configuration changes. This happens to work pretty nicely with this `@Nested` pointing to the actual tasks ☺️
