### PR TITLE
Fix overflow of long underscore separated names in HTML

### LINKED ISSUE #3093: Long undescore divided names doesn't fit on page
Similar to  #2516 but more rare (require an even longer name)

image

Works fine for CamelCase

image

**Installation**
- Dokka version: 1.9.0

### PR DESCRIPTION
**Pull request by seelchen**
This PR makes underscore separated names breakable after each underscore similar to how names separated by dots are rendered.

Resolves #3093.

### CODE REVIEW

**Comment by seelchen** [comment]
Hi @IgnatBeresnev, could you please review my PR if you have time?

**Comment by IgnatBeresnev** [comment]
@seelchen hi! thank you for the contribution, and sorry for the delay with review. The two PRs you've submitted cover a pretty wide area of Dokka, so we need some extra time to make sure it's aligned with Dokka's design requirements, and that it doesn't break any corner cases

**Comment by seelchen** [comment]
Hi @IgnatBeresnev  and @whyoleg, are there any updates on the review of this PR?

File: dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt [hunk 1]
```diff
@@ -23,14 +23,17 @@ public fun FlowContent.buildTextBreakableAfterCapitalLetters(name: String, hasLa
     }
 }
 
-public fun FlowContent.buildBreakableDotSeparatedHtml(name: String) {
-    val phrases = name.split(".")
+/**
+ * Makes [name] breakable after each occurrence of [breakableChar].
+ */
+public fun FlowContent.buildBreakableCharSeparatedHtml(name: String, breakableChar: Char) {
```
Comment (whyoleg) [inline dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt:29]: Could you please additionally to new function leave `buildBreakableDotSeparatedHtml` for ABI/API compatibility with `Deprecated` annotation and delegated implementation to `buildBreakableCharSeparatedHtml(name, '.')`?

File: dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt [hunk 2]
```diff
@@ -23,14 +23,17 @@ public fun FlowContent.buildTextBreakableAfterCapitalLetters(name: String, hasLa
     }
 }
 
-public fun FlowContent.buildBreakableDotSeparatedHtml(name: String) {
-    val phrases = name.split(".")
+/**
+ * Makes [name] breakable after each occurrence of [breakableChar].
```
Comment (whyoleg) [inline dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt:27]:
```suggestion
 * Makes [name] breakable by inserting `<wbr>` element after each occurrence of [breakableChar].
```

**Review by whyoleg — CHANGES_REQUESTED** [review]
Hey!
Thank you for PR and sorry for long review.
Could you please rebase PR onto the latest `master` and fix some minor comments?

File: dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt (hunk 1 above)
Comment (seelchen) [reply dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt:40]: Done in [2ca4577](https://github.com/Kotlin/dokka/pull/3240/commits/2ca4577c0e2e488e621b87979218f634595ac356) :+1:

File: dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt (hunk 2 above)
Comment (seelchen) [reply dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/renderers/html/htmlFormatingUtils.kt]: Done in [2ca4577](https://github.com/Kotlin/dokka/pull/3240/commits/2ca4577c0e2e488e621b87979218f634595ac356) :+1:

**Review by whyoleg — APPROVED** [review]
Thank you for the contribution!
Will merge after the test completion
