### PR TITLE
Handles errors and fixes minor bugs

### LINKED ISSUE #581: Add information about warnings and errors count after generation.
`DokkaConsoleLogger` is logging information about warnings count after completed generation. To complete this task add similar behavior for all runners and both warnings and exceptions.

### PR DESCRIPTION
**Pull request by BarkingBad**
Fixes #581

### CODE REVIEW

File: core/src/main/kotlin/DokkaBootstrapImpl.kt [hunk 1]
```diff
@@ -39,11 +43,23 @@ class DokkaBootstrapImpl : DokkaBootstrap {
...
-            consumer.accept("error", message)
+            consumer.accept("error", message).also { errorsCount++ }
+        }
+
+        override fun report() {
+            if (warningsCount > 0 || errorsCount > 0) {
+                println("Generation completed with $warningsCount warning" +
+                        (if(DokkaConsoleLogger.warningsCount == 1) "" else "s") +
+                        " and $errorsCount error" +
+                        if(DokkaConsoleLogger.errorsCount == 1) "" else "s"
```
Comment (Kordyjan) [inline core/src/main/kotlin/DokkaBootstrapImpl.kt]: Unnecessary `DokkaConsoleLogger`.
