### PR TITLE
Correctly handle case when we have `internal expect` but `public actual` declarations

### LINKED ISSUE #3633: Public actual declarations are not shown in docs if expect is internal
**Describe the bug**
```
// common source set
internal expect fun foo() {}

// actual platform 1 (e.g. Native)
/** foo docs */
public actual fun foo() {}

// actual platform 2 (e.g. Wasm)
internal actual fun foo() {}
```

Actualizing an internal expect declaration with a public actual declarations is [allowed in KMP](https://kotlinlang.org/docs/whatsnew20.html#different-visibility-levels-of-expected-and-actual-declarations) (at least for functions, but we use it for classifiers as well in stdlib). However if such an internal expect declaration is introduced, its public actual counterparts are no longer shown in documentation.

**Expected behavior**
Public actual declarations should continue being rendered for individual platforms as if there's no expect declared.

**To Reproduce**
Kotlin branch: [rr/stdlib/docs-internal-expect-public-actual](https://github.com/JetBrains/kotlin/compare/rr/stdlib/docs-internal-expect-public-actual)
Docs build: https://buildserver.labs.intellij.net/buildConfiguration/Kotlin_KotlinDev_LibraryReferenceLatestDocs/509723400?buildTab=artifacts
Example declaration: `kotlin.system.exitProcess`
- before introducing expect: https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.system/exit-process.html
- after introducing expect: https://buildserver-artifacts.labs.intellij.net/presignedTokenAuth/1002a5ef-c5bb-4488-b578-9156ba6e24bd/repository/download/Kotlin_KotlinDev_LibraryReferenceLatestDocs/509723400:id/latest-version.zip!/all-libs/kotlin-stdlib/kotlin.system/index.html

**Installation**
- Operating system: macOS/Windows/Linux
- Build tool: Gradle v7.6
- Dokka version: 2.0.20-dev-334

**Context**
We need to use internal expects for public declarations for proper K2 stdlib compilation of the code shared between Native and Wasm.

### PR DESCRIPTION
**Pull request by whyoleg**
fixes #3633

### CODE REVIEW

File: dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/transformers/documentation/DefaultDocumentableMerger.kt [hunk 1]
```diff
@@ -106,9 +106,20 @@ public class DefaultDocumentableMerger(context: DokkaContext) : DocumentableMerg
...
 
+        fun processClashingElements(elements: List<T>) =
+            elements.map { it to it.sourceSets }
+                .groupBy { it.first.dri }
+                .values
+                .flatMap(::mergeClashingElements)
 
         fun analyzeExpectActual(sameDriElements: List<T>): List<T> {
             val (expects, actuals) = sameDriElements.partition { it.expectPresentInSet != null }
+            // It's possible that there are no `expect` declarations, but there are `actual` declarations,
```
Comment (vmishenev) [inline dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/transformers/documentation/DefaultDocumentableMerger.kt:117]: LGTM
But I am not sure about treating such declarations as clashing. 
It works for stdlib since `mergeImplicitExpectActualDeclarations=true` is enabled. In other projects, the documentation would have separated pages that can look inconsistent regarding normal expect/actual declarations. 
Is there a reason to have clashing declarations instead of a merged one?

**Review by vmishenev — APPROVED** [review]

File: dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/transformers/documentation/DefaultDocumentableMerger.kt (hunk 1 above)
Comment (whyoleg) [reply dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/transformers/documentation/DefaultDocumentableMerger.kt:117]: Yeah, good idea. Will see what can be done here.

**Review by vmishenev — APPROVED** [review]
