### PR TITLE
Fix invisible packages for module names with space

### LINKED ISSUE #3011: Custom module name leads to hidden packages for maven runner
Configure the Dokka Maven plugin with custom module name:
```xml
<plugin>
                <groupId>org.jetbrains.dokka</groupId>
                <artifactId>dokka-maven-plugin</artifactId>
                <version>1.8.10</version>
<!--                <version>1.7.20</version>-->
                <executions>
                    <execution>
                        <phase>pre-site</phase>
                        <goals>
                            <goal>dokka</goal>
                        </goals>
                    </execution>
                </executions>

                <configuration>
                    <moduleName>Dokka Maven Project</moduleName>
                </configuration>
            </plugin>
```

As a result, rendered documentation will filter out all sources:
image

The issue appeared in `1.8.10`. For `1.7.20`, it works fine. Also, it does not reproduce for Gradle runner.

### PR DESCRIPTION
**Pull request by IgnatBeresnev**
Fixes #3011 

Read my comment to understand what exactly the problem was: https://github.com/Kotlin/dokka/issues/3011#issuecomment-1568620493

There are better ways to resolve this problem, but this is the only solution that I could think of that wouldn't lead to a lot of other regressions and problems (including for Gradle users), because the value of `scopeId` is used in other parts of the code as well, such as sorting and anchor links, so changing it would lead to regression in behaviour.

One could argue that module names should not contain spaces - I would agree, but the `moduleName` property is used as the parent project name, so the desire to change it to something human-readable is quite understandable, and if we fix it know it's likely going to lead to bug reports. It really needs to be a separate property..

Ideally, a better solution should be implemented as part of #2779 - the current logic is quite error-prone and difficult to navigate..

### CODE REVIEW

File: plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt [hunk 1]
```diff
@@ -982,8 +987,5 @@ private val PageNode.isNavigable: Boolean
 private fun PropertyContainer<ContentNode>.extraHtmlAttributes() = allOfType<SimpleAttr>()
 private fun PropertyContainer<ContentNode>.extraTabbedContentType() = this[TabbedContentTypeExtra]
 
-private val ContentNode.sourceSetsFilters: String
-    get() = sourceSets.sourceSetIDs.joinToString(" ") { it.toString() }
```
Comment (IgnatBeresnev) [inline plugins/base/src/main/kotlin/renderers/html/HtmlRenderer.kt:986]: Before every table-row, there's an invisible link - I think it's used by the anchor link to focus on the right row. This property was used for the filter value in it, but I couldn't understand if it was actually needed to be present - made no difference upon testing.

**Review by atyrin — APPROVED** [review]
👌
