### PR TITLE
Fix param tag for type parameter on implicit primary constructor

### LINKED ISSUE #4145: [K2] Missing param tag for type parameter on implicit primary constructor
```
/** @param T a type */
class Foo<T>
```

With K1, the `documentation` on the `DFunction` for the implicit primary constructor of `Foo` is
`DocumentationNode(children=[Param(root=CustomDocTag(children=[P(children=[Text(body=a type, children=[], params={})], params={})], params={}, name=MARKDOWN_FILE), name=T)])`.

With K2, the `documentation` for the constructor `DFunction` is empty.

Possibly related to #3348?

### PR DESCRIPTION
**Pull request by vmishenev**
fix #4145

### CODE REVIEW

File: dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt [hunk 1]
```diff
@@ -98,6 +98,7 @@ internal fun KaSession.findKDoc(symbol: KaSymbol): KDocContent? {
             val paramSections = kdoc.findSectionsContainingTag(KDocKnownTag.PARAM)
             return KDocContent(constructorSection, paramSections)
         }
+        return KDocContent(kdoc.getDefaultSection(), kdoc.getAllSections())
```
Comment (vmishenev) [inline dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt:103]: This simply duplicates the logic of IDE's `lookupOwnedKDoc`

Comment (whyoleg) [reply dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/KDocProvider.kt:103]: You mean the one `lookupOwnedKDoc` which is located below in this file?
In any case, it would be nice to add a comment that the logic here should be duplicated to `lookupOwnedKDoc` below if we can't extract it

**Review by whyoleg — APPROVED** [review]
