### PR TITLE
Make MarkdownParser output text instead of broken links

### LINKED ISSUE #1345: S3 Coroutines unresolved links
Related to markdown on the module page

### PR DESCRIPTION
**Pull request by kamildoleglo**
MarkdownParser should also output info about the unresolved link and its location. This however should be done properly when refactoring the parser 

Closes #1345

### CODE REVIEW

**Comment by sellmair** [comment]
Do you want this being merged into 1.4.0?

File: plugins/base/src/main/kotlin/parsers/MarkdownParser.kt [hunk 1]
```diff
@@ -159,17 +161,37 @@ class MarkdownParser(
...
+                    MarkdownElementTypes.INLINE_LINK,
+                    params = params,
+                    children = linkText.children.drop(1).dropLast(1).evaluateChildren(),
+                    dri = dri
+                )
+            }
+        }
+
+        private fun String.isRemoteLink() = try {
+            URL(this)
```
Comment (sellmair) [inline plugins/base/src/main/kotlin/parsers/MarkdownParser.kt:191]: I was looking for some more straight-forward way of checking this. 
@Kordyjan Do you know a better method? 🙄

**Comment by kamildoleglo** [comment]
> Do you want this being merged into 1.4.0?

Not sure 🤔 We can do that I think

File: plugins/base/src/main/kotlin/parsers/MarkdownParser.kt (hunk 1 above)
Comment (sellmair) [reply plugins/base/src/main/kotlin/parsers/MarkdownParser.kt:191]: I think this is the way many people do this. It's not the nicest API, but seems to work for others as well 🤷
