### PR TITLE
Fix package and module description truncation in javadoc

### LINKED ISSUE #2055: Generated package-level javadoc truncates all documentation after the first sentence.
**Describe the bug**
Generated javadoc includes only the first sentence of package-level documentation on the package page. All package-level documentation after the first sentence is dropped, and does not appear anywhere in the generated javadoc.

**Expected behaviour**
The package page for a given package should include all the documentation written for that package.

**Screenshots**
From the reproduction example project, javadoc has only the first sentence of documentation:
screenshot
Compare the generated kotlindoc, which contains the entire package documentation:
screenshot

**To Reproduce**
Reproduction example project is at https://github.com/whbboyd/dokka-javadoc-bug

**Installation**
- Operating system: Linux
- Build tool: Maven 3.6.0/OpenJDK 11.0.12
- Dokka version: 1.5.0 (also reproduced with 1.4.32)

**Are you willing to provide a PR?**
If I can be pointed to likely culprit code, I can take a crack at writing a PR.

### PR DESCRIPTION
**Pull request by BlackAnubis7**
Fixes #2055

### CODE REVIEW

File: plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt [hunk 1]
```diff
@@ -77,4 +78,65 @@ internal class JavadocModuleTemplateMapTest : AbstractJavadocTemplateMapTest() {
...
+            ABC
+            
+            /src/source0.kt
+            package com.test.package0
+            class Test
+            """,
+            configuration = config.copy(
+                sourceSets = config.sourceSets.map { sourceSet ->
+                    sourceSet.copy(
+                        includes = setOf(File("src/module.md").also {println(it.absolutePath)})
```
Comment (IgnatBeresnev) [inline plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt:98]: Leftover from debugging? Could be confusing to see a random path printed out of the blue otherwise

```suggestion
                        includes = setOf(File("src/module.md"))
```

File: plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt [hunk 2]
```diff
@@ -77,4 +78,65 @@ internal class JavadocModuleTemplateMapTest : AbstractJavadocTemplateMapTest() {
             assertEquals(DRI("com.test.package1"), assertIsInstance<RowJavadocListEntry>(list[1]).link.dri.single())
         }
     }
+
+    @Test
+    fun `single class with package documentation (kotlin)`() {
```
Comment (IgnatBeresnev) [inline plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt:83]: It seems to be about module documentation?
```suggestion
    fun `single class with module documentation (kotlin)`() {
```

File: plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt [hunk 3]
```diff
@@ -77,4 +78,65 @@ internal class JavadocModuleTemplateMapTest : AbstractJavadocTemplateMapTest() {
...
+        ) {
+            val modulePage = singlePageOfType<JavadocModulePageNode>()
+
+            val map = modulePage.templateMap
+            assertEquals("<p>ABC</p>", map["subtitle"].toString().trim())
+        }
+    }
+
+    @Test
+    fun `single class with long package documentation (kotlin)`() {
```
Comment (IgnatBeresnev) [inline plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt:112]:
```suggestion
    fun `single class with long module documentation (kotlin)`() {
```

File: plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt [hunk 4]
```diff
@@ -77,4 +78,65 @@ internal class JavadocModuleTemplateMapTest : AbstractJavadocTemplateMapTest() {
...
+            Veritatis nam eaque sequi laborum voluptas voluptate aut.
+            
+            /src/source0.kt
+            package com.test.package0
+            class Test
+            """,
+            configuration = config.copy(
+                sourceSets = config.sourceSets.map { sourceSet ->
+                    sourceSet.copy(
+                        includes = setOf(File("src/module.md").also {println(it.absolutePath)})
```
Comment (IgnatBeresnev) [inline plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt:130]:
```suggestion
                        includes = setOf(File("src/module.md"))
```

File: plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt [hunk 5]
```diff
@@ -77,4 +78,65 @@ internal class JavadocModuleTemplateMapTest : AbstractJavadocTemplateMapTest() {
...
+                    )
+                },
+                moduleName = "module1"
+            )
+        ) {
+            val modulePage = singlePageOfType<JavadocModulePageNode>()
+
+            val map = modulePage.templateMap
+            assertEquals("<p>Aliquam rerum est vel. Molestiae eos expedita animi repudiandae sed commodi. Omnis qui ducimus ut et perspiciatis sint.</p><p>Veritatis nam eaque sequi laborum voluptas voluptate aut.</p>", map["subtitle"].toString().trim())
```
Comment (IgnatBeresnev) [inline plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt:139]: Could multiline string literals be used in this case? Having extremely long lines adds annoying horizontal scrolling and is not very good for readbility

```suggestion
            val expectedText = """
                <p>Aliquam rerum est vel. Molestiae eos expedita animi repudiandae sed commodi. 
                Omnis qui ducimus ut et perspiciatis sint.</p>
                <p>Veritatis nam eaque sequi laborum voluptas voluptate aut.</p>
            """.trimIndent()
            
            assertEquals(expectedText, map["subtitle"].toString().trim())
```

Here and in other two places

File: plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocPackageTemplateMapTest.kt [hunk 6]
```diff
@@ -96,31 +117,75 @@ internal class JavadocPackageTemplateMapTest : AbstractJavadocTemplateMapTest()
             package com.test.package0
             class Test
             """,
+            configuration = config.copy(
+                sourceSets = config.sourceSets.map { sourceSet ->
+                    sourceSet.copy(
+                        includes = setOf(File("src/packages.md").also {println(it.absolutePath)})
```
Comment (IgnatBeresnev) [inline plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocPackageTemplateMapTest.kt:123]:
```suggestion
                        includes = setOf(File("src/packages.md"))
```

File: plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocPackageTemplateMapTest.kt [hunk 7]
```diff
@@ -96,31 +117,75 @@ internal class JavadocPackageTemplateMapTest : AbstractJavadocTemplateMapTest()
...
+
+            /src/source0.kt
+            package com.test.package0
+            class Test
             """,
             configuration = config.copy(
                 sourceSets = config.sourceSets.map { sourceSet ->
                     sourceSet.copy(
-                        includes = setOf(File("packages.md"))
+                        includes = setOf(File("src/packages.md").also {println(it.absolutePath)})
```
Comment (IgnatBeresnev) [inline plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocPackageTemplateMapTest.kt:180]:
```suggestion
                        includes = setOf(File("src/packages.md"))
```

**Review by IgnatBeresnev — COMMENTED** [review]
Well done! Left some minor comments, otherwise I'm ready to merge it

File: plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt (hunk 1 above)
Comment (BlackAnubis7) [reply plugins/javadoc/src/test/kotlin/org/jetbrains/dokka/javadoc/JavadocModuleTemplateMapTest.kt]: Yes, it was a leftover from debugging. Removed

**Review by IgnatBeresnev — APPROVED** [review]
LGTM, thank you once again!
