### PR TITLE
Fix merging expect-actual declarations

### LINKED ISSUE #3798: Generation fails for expect declared in intermediate source set
Create a KMP project with jvm + linuxX64 + macosX64. And such code in source sets:
```Kotlin
// nativeMain
expect fun shared()

// linuxX64Main, macosX64Main
actual fun shared(){}
```

```
Caused by: java.lang.IllegalArgumentException: Collection has more than one element.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:605)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.mergeExpectActual$analyzeExpectActual(DefaultDocumentableMerger.kt:119)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.mergeExpectActual(DefaultDocumentableMerger.kt:136)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.mergeWith(DefaultDocumentableMerger.kt:141)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger$invoke$1$3.invoke(DefaultDocumentableMerger.kt:35)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger$invoke$1$3.invoke(DefaultDocumentableMerger.kt:33)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.merge(DefaultDocumentableMerger.kt:55)
	at org.jetbrains.dokka.transformers.documentation.DefaultDocumentableMerger.invoke(DefaultDocumentableMerger.kt:33)
	at org.jetbrains.dokka.base.generation.SingleModuleGeneration.mergeDocumentationModels(SingleModuleGeneration.kt:82)
	at org.jetbrains.dokka.base.generation.SingleModuleGeneration.generate(SingleModuleGeneration.kt:38)
	at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:34)
	at org.jetbrains.dokka.DokkaGenerator$generate$1.invoke(DokkaGenerator.kt:27)
	at org.jetbrains.dokka.DokkaGeneratorKt.timed(DokkaGenerator.kt:82)
	at org.jetbrains.dokka.DokkaGeneratorKt.access$timed(DokkaGenerator.kt:1)
	at org.jetbrains.dokka.DokkaGenerator.generate(DokkaGenerator.kt:27)
	at org.jetbrains.dokka.DokkaBootstrapImpl.generate(DokkaBootstrapImpl.kt:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.jetbrains.dokka.gradle.DelegatedInvocationHandler.invoke(automagicTypedProxy.kt:44)
	at jdk.proxy4/jdk.proxy4.$Proxy127.generate(Unknown Source)
	at org.jetbrains.dokka.gradle.AbstractDokkaTask$generateDocumentation$1$1.run(AbstractDokkaTask.kt:232)
```

**Installation**
- Dokka version: 2.0.20-dev-357
- DGPv1 / K1 or K2

[dokka-repros.zip](https://github.com/user-attachments/files/16966581/dokka-repros.zip)

### PR DESCRIPTION
**Pull request by vmishenev**
Fixes #3798

This bug appeared due to https://github.com/Kotlin/dokka/pull/3662
The merging order depends on the order of source sets. 
E.g. if we have the following order of source sets:` (expect, actual1, actual2)`. `DefaultDocumentableMerger` has a pairwise merger. So a declaration will be merged as follows:` (expect, actual1)`, then` (expect, actual1, actual2)`.

In the case of the original issue: the order of source sets `(actual1, actual2, expect)`.
Before https://github.com/Kotlin/dokka/pull/3662, it does not allow to merge actuals without an expect source set.
After that, we have a state when there is `(actual1, actual2)` that leads to an exception #3798.

### CODE REVIEW

File: dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/transformers/documentation/DefaultDocumentableMerger.kt [hunk 1]
```diff
@@ -116,9 +116,11 @@ public class DefaultDocumentableMerger(context: DokkaContext) : DocumentableMerg
                 listOf(actuals to actuals.flatMap { it.sourceSets }.toSet())
             } else expects.map { expect ->
                 val actualsForGivenExpect = actuals.filter { actual ->
-                    dependencyInfo[actual.sourceSets.single()]
+                    actual.sourceSets.all {
```
Comment (whyoleg) [inline dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/transformers/documentation/DefaultDocumentableMerger.kt:119]: could you please add some info in PR description / comment in code, on why this should be like this?

File: dokka-subprojects/plugin-base/src/test/kotlin/expectActuals/ExpectActualsTest.kt [hunk 2]
```diff
@@ -380,4 +381,58 @@ class ExpectActualsTest : BaseAbstractTest() {
             )
         }
     }
+
+
+    @Test
+    fun `should work with the reversed order of source sets #3798`() {
```
Comment (whyoleg) [inline dokka-subprojects/plugin-base/src/test/kotlin/expectActuals/ExpectActualsTest.kt:387]: would be nice to additionally have a test more similar to the issue #3798, where we do have an `expect` in shared source-set (e.g. `native`) and not in `common`

Also, it's not really obvious, why `reverse order` somehow affects the changes in PR for me...

**Review by whyoleg — CHANGES_REQUESTED** [review]
I'm not sure, that I understand, why the proposed changes fixes the original issue :(

File: dokka-subprojects/plugin-base/src/test/kotlin/expectActuals/ExpectActualsTest.kt (hunk 2 above)
Comment (vmishenev) [reply dokka-subprojects/plugin-base/src/test/kotlin/expectActuals/ExpectActualsTest.kt:387]: [DefaultDocumentableMerger.kt](https://github.com/Kotlin/dokka/pull/3875/files/ab76464f4ee06e320c68e57e74e8871e8b9ffbf6#diff-00add2e0f152afbda9fba4e4e7e8d666bcfb619525d9d73bb211e7776e7bd1a9) does not depend on a platform and not use it at all.


The configuration from the issue just affects the order of source sets. Intermediate source sets do not trigger the issue without the special order.
I have updated the description of the PR. Feel free to let me know if you have questions.

**Review by whyoleg — APPROVED** [review]
Nice!
Thanks for the explanation!
