### PR TITLE
Option to fail on warning

### LINKED ISSUE #459: Option to fail on warning
It would be useful to have an option to fail the build when warnings are found so this can be enforced by CI builds.

### PR DESCRIPTION
**Pull request by sellmair**
Closes #459

### CODE REVIEW

File: runners/cli/src/main/kotlin/cli/main.kt [hunk 1]
```diff
@@ -48,6 +48,10 @@ open class GlobalArguments(parser: DokkaArgumentsParser) : DokkaConfiguration {
 
     override val impliedPlatforms: List<String> = emptyList()
 
+    override val failOnWarning: Boolean by parser.singleFlag(
+        listOf("-failOnWarning"), "Fail dokka task if at least one warning was reported"
```
Comment (sellmair) [inline runners/cli/src/main/kotlin/cli/main.kt:52]: Alternative: "-warningPolicy=strict"
