### PR TITLE
Do not leak unknown asset paths into HTML

### LINKED ISSUE #3040: Directory path of `customAssets` is being displayed on the main index page
**Describe the bug**

Providing a directory to `DokkaBaseConfiguration.customAssets` leads to raw text being displayed on the main index page above the logo.
This is used to scope assets in the `images/` directory to prevent collisions.

**Screenshots**

image

**Dokka configuration**
Configuration of dokka used to reproduce the bug

```Kotlin
pluginConfiguration<DokkaBase, DokkaBaseConfiguration> {
    customAssets = listOf(file("test")) // The test directory contains the actual assets
}
```

**Installation**
- Operating system: macOS
- Build tool: Gradle v8
- Dokka version: 1.8.20

**Additional context**

Here is a snippet of the html output:

```html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
    <title>All modules</title>
    <link href="images/logo-icon.svg" rel="icon" type="image/svg">
<script type="text/javascript" src="scripts/sourceset_dependencies.js" async="async"></script>
<link href="styles/style.css" rel="Stylesheet">
<link href="styles/jetbrains-mono.css" rel="Stylesheet">
<link href="styles/main.css" rel="Stylesheet">
<link href="styles/prism.css" rel="Stylesheet">
<link href="styles/logo-styles.css" rel="Stylesheet">
<script type="text/javascript" src="scripts/clipboard.js" async="async"></script>
<script type="text/javascript" src="scripts/navigation-loader.js" async="async"></script>
<script type="text/javascript" src="scripts/platform-content-handler.js" async="async"></script>
<script type="text/javascript" src="scripts/main.js" defer="defer"></script>
<script type="text/javascript" src="scripts/prism.js" async="async"></script>
<script type="text/javascript" src="scripts/symbol-parameters-wrapper_deferred.js" defer="defer"></script>
images/test</head>
<body>
...
</body>
```
Add any other context about the problem here

**Are you willing to provide a PR?**

Yes

### PR DESCRIPTION
**Pull request by IgnatBeresnev**
Fixes #3040

### CODE REVIEW

File: plugins/base/src/main/kotlin/renderers/html/innerTemplating/DefaultTemplateModelFactory.kt [hunk 1]
```diff
@@ -112,7 +112,11 @@ class DefaultTemplateModelFactory(val context: DokkaContext) : TemplateModelFact
                     it.isImage() -> link(href = if (it.isAbsolute) it else "$pathToRoot$it")
                     else -> null
                 }
-            } ?: it)
```
Comment (IgnatBeresnev) [inline plugins/base/src/main/kotlin/renderers/html/innerTemplating/DefaultTemplateModelFactory.kt:115]: The bug was with `?: it`

File: plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt [hunk 2]
```diff
@@ -205,4 +207,93 @@ class ResourceLinksTest : BaseAbstractTest() {
             }
         }
     }
+
+    @Test
+    fun `should not add unknown resources to the end of the head section`() {
```
Comment (IgnatBeresnev) [inline plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt:212]: Not completely satisfied with the test as it will break when other resources are added, but couldn't think of anything better to check that nothing else was added to the end :(

File: plugins/base/src/test/kotlin/transformerBuilders/PageTransformerBuilderTest.kt [hunk 3]
```diff
@@ -177,40 +177,6 @@ class PageTransformerBuilderTest : BaseAbstractTest() {
         }
     }
 
-    @Test
-    fun `should load script as defer if name ending in _deferred`() {
```
Comment (IgnatBeresnev) [inline plugins/base/src/test/kotlin/transformerBuilders/PageTransformerBuilderTest.kt:181]: I wrote this test a while ago, and at the time I couldn't find a good place for it, but I think having it in `ResourceLinksTest` is better now, so I moved it there.

File: plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt (hunk 2 above)
Comment (vmishenev) [inline plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt:212]: Additionally, you can check `head().children` are only tags, no text block.

**Review by vmishenev — APPROVED** [review]

File: plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt [hunk 4]
```diff
@@ -205,4 +207,93 @@ class ResourceLinksTest : BaseAbstractTest() {
...
+            configuration,
+            pluginOverrides = listOf(writerPlugin)
+        ) {
+            renderingStage = { _, _ ->
+                val generatedFiles = writerPlugin.writer.contents
+
+                val testPageHeadHtml = generatedFiles
+                    .getValue("root/test/-test/-test.html")
+                    .let { Jsoup.parse(it) }
+                    .select("head")
```
[the remark this answers is not in the document]
Comment (IgnatBeresnev) [reply plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt:250]: Indeed, I totally forgot that there are accessor methods for the main tags/sections 👍 

Fixed

File: plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt (hunk 2 above)
Comment (IgnatBeresnev) [reply plugins/base/src/test/kotlin/resourceLinks/ResourceLinksTest.kt]: Nice idea! I definitely like it more than my current test.

Re-wrote it to check that there are no text nodes
