### PR TITLE
[K2] Fix order of KDoc link candidates

### LINKED ISSUE #3375: [K2] `List` reference leads to the stdlib collections package
```Kotlin
/**
 * ref to [List] or [Set]
 */
fun x(){}
```

`List` link leads to https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/ instead of https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-list/ (in K1).
For `Set` the link is correct.

**Installation**
- Dokka version: 1.9.20

Parent: #3328

### PR DESCRIPTION
**Pull request by vmishenev**
Fixes #3375

### CODE REVIEW

**Review by whyoleg — APPROVED** [review]

File: dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/ResolveKDocLink.kt [hunk 1]
```diff
@@ -78,5 +78,20 @@ internal fun KtAnalysisSession.resolveKDocLinkToDRI(link: KDocLink): DRI? {
...
+ */
+private var linkCandidatesComparator: Comparator<KtSymbol> = compareBy{
+    when(it) {
+        is KtClassifierSymbol -> 1
+        is KtPackageSymbol -> 2
+        is KtFunctionSymbol -> 3
+        is KtVariableSymbol-> 4
+        else -> 5
+    }
+}
```
Comment (IgnatBeresnev) [inline dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/ResolveKDocLink.kt:97]: Could you please cover all cases with tests? I see a test for the initial bug where class < function, which is good, and it would be very helpful to make sure other cases don't break either. Especially once KT-64190 is fixed - it will help us verify that it was implemented the way we expected

And a side question: can there be two symbols of the same type? For example, two `KtClassifierSymbol`? Asking in case there's a non-obvious corner case related to source sets, expect/actual, `internal` visibility, java interop or something else? If there is, does it make sense to add a second comparison with `thenBy { it.name }` or something similar, to make it predictable?

Comment (vmishenev) [reply dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/ResolveKDocLink.kt:97]: > can there be two symbols of the same type? 

It is possible for `KtFunctionSymbol` when there are overloads. In this case, the order is not specified at all and it does not affect a result URL. It is not easy to make the order like in K1 on Dokka's side and consistent with IDEA. See added `tests for overloads`

For the other types of symbols, it is difficult to come up with a case when we have the same name in the same scope.

Comment (vmishenev) [reply dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/kdoc/ResolveKDocLink.kt:97]: I think a stable order of overloads can be addressed in #3250

**Comment by Luqman2302** [comment]
gh pr checkout 3447
