### PR TITLE
Fix checking for annotations when rendering constructor keyword

### LINKED ISSUE #3426: Excessive `constructor` keyword rendered in class signatures
The `constructor` keyword is in some cases rendered excessively as it's public and doesn't have any parameters.

image

### PR DESCRIPTION
**Pull request by whyoleg**
Fixes #3426

There are 2 cases when annotation is not rendered and so no `constructor` keyword should be rendered:
1. when annotation is not annotated with `MustBeDocumented`
2. when annotation is ignored (and so handled in some other way, like `Deprecated`)

Note: PR has small API/ABI changes (no breaking changes), that's because ignored annotations are ignored later in pipeline, only during rendering. We can't ignore annotations in `JvmSignatureUtils`, as we need all annotations in other places to make a special handling of those ignored annotations (like `Deprecated`).
Also, we can introduce something like `Annotation.shouldBeRendered` instead of `Annotation.isIgnored` inside `JvmSignatureUtils`, but to use it under the hood in `annotationsInline`/`annotationsBlock` we will need to break API/ABI (or introduce new declaration + deprecate old one) as on current moment `ignored` annotations there provided explicitly...
So I've decided not to go this road.
If we think that it's fine to break API/ABI in `JvmSignatureUtils` and its inheritors (can be seen in API dump changes), then I can update PR.

### CODE REVIEW

File: dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt [hunk 1]
```diff
@@ -1366,6 +1366,63 @@ class SignatureTest : BaseAbstractTest() {
         }
     }
 
+    @OnlyDescriptors("#3354")
+    @Test
+    fun `should not render constructor for Any from Wasm sources`() = testRender(
```
Comment (vmishenev) [inline dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt:1371]: _nitpick:_ I would prefer to have a more general name for this test, e.g. `should not render constructor without a renderable annotation`

**Review by vmishenev — APPROVED** [review]

File: dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt (hunk 1 above)
Comment (whyoleg) [reply dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt:1371]: There is such test below, though, named a little more explicit.
This specific case is what was happening in original issue. Mostly to check, that it works the same for `kotlin` package and `builtin` class, so Im not sure, what will be the best name here.

Comment (vmishenev) [reply dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt:1371]: Among other tests this name made me think about a specific logic for Any (we have such a one) or wasm source set.

Comment (whyoleg) [reply dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt:1371]: yeah, I see why there is a confusion... do you have any other idea on how to name this test, so that the intention will be clear?
Does something like this will be better may be `should not render constructor without a renderable annotation for kotlin.Any`? I mean, while there is no special casing for `kotlin.Any`, I would still expect to have a test that checks specifically reported problem here, as kotlin builtins are specific things and so it's good to have tests for them.

Comment (vmishenev) [reply dokka-subprojects/plugin-base/src/test/kotlin/signatures/SignatureTest.kt:1371]: I think the name below can be reused as the test has the same logic. 
`should not render parameterless constructor with annotation without mustBeDocumented annotation - for kotlin.Any `

**Review by IgnatBeresnev — APPROVED** [review]
